-- CREATE DATABASE FOR COLLAGE 
CREATE DATABASE COLLAGE;

-- FOR USE DATABASE
USE COLLAGE;

-- FOR CREATE TABLE
CREATE TABLE STUDENT(
STDID INT PRIMARY KEY,
STDNAME VARCHAR(10) NOT NULL,
STDAGE INT NOT NULL
);


SELECT * FROM STUDENT;

-- FOR INSERT RECORD 
INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(1,'SALMAN',23);
INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(2,'AKSAY',63);

-- FOR SHOW DATA
SELECT * FROM STUDENT;

-- SHOW ALL DATABASE '
SHOW databases;

-- SHOW ALL TABLES FROM CURRENT DATABASE.
SHOW TABLES;

-- FOR DELETE TABLE
-- DROP TABLE STUDENT;

-- ADD MULTIPLE RECORD IN TABLE AT ONE TIME.
INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(3,'SAHDEV',22),
(4,'VISHAL',15),
(5,'UJAS',90),
(6,'KAPIL',10),
(7,'UTSAV',100);

-- FOR SHOW TABLE
SELECT * FROM STUDENT;

-- FOR SHOW PATRTICLUAR COLUMN FROM TABLES.
SELECT STDID,STDNAME,STDAGE FROM STUDENT;

-- ADD COLUMN IN TABLE
ALTER TABLE STUDENT ADD STDMO_NO bigint(10);

-- REMOVE SPECIFIC COLUMN FROM TABLE.
ALTER TABLE STUDENT DROP COLUMN STDMO_NO;

-- //////////////  NEW DATABASE ///////////// --

CREATE DATABASE SCHOOL;

USE SCHOOL;

CREATE TABLE STUDENT(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);


INSERT INTO STUDENT(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(105,"RAMESH",78,"D","PUNE");

INSERT INTO STUDENT(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(101,"ANIL",78,"D","PUNE"),
(102,"BHUMIKA",93,"C","MUMBAI"),
(103,"CHETAN",85,"B","DELHI"),
(104,"DHRUV",96,"A","BANGLORE");

-- SHOW DATA 
SELECT * FROM STUDENT;

-- FOR DELETE ONLY DATA NOT TABLE.
-- TRUNCATE TABLE STUDENT;

-- SHOW PARTICULAR A SINGLKE COLUMN
SELECT NAME,CITY FROM STUDENT; 

-- FOR SHOE A UNIQUE DATA FROM PARTICULAR FIELD
SELECT  DISTINCT CITY FROM STUDENT;

-- FOR A SPECIAL DATA WITH CONDITION
SELECT * FROM STUDENT WHERE CITY = "BANGLORE";





